### ISSUE TITLE
Better2DGraph widget issue

### ISSUE THREAD

**Issue by pawelkulig1** [LemurPwned/VISM#29]
- [x] Not resizing correctly inside pane
- [x] Some synchronization/redrawing issues
- [x] Need to add more customization options
- [x] Graph not resizing correctly, and not centered inside Widget

**Comment by LemurPwned** [comment]
I will try to work this issue out while pull requests are not fully resolved

**Comment by LemurPwned** [comment]
I think this issue has fully resolved, if not that is not a problem solely of that particular 2d widget but general window resizing

**Comment by pawelkulig1** [comment]
Fixing windows resizing problem haven't solved that. I will try to find solution once again.

**Comment by pawelkulig1** [comment]
I think I have found solution to fix this, this may take me a lot of time to resolve, for now I would recommend to exclude this widget, from available widgets because we have another working widget that is working properly.

**Comment by LemurPwned** [comment]
Solution: 
the pyqtgraph widget has been created twice -> once because the Canvas2d upgraded class has inherited PlotWidet and then called the default constructor of a parent class, and secondly, this time by intention, in the __init__ function of child class. This caused the two to overlay and thus cause problems. 
Removing inheritance on pyqtgraphs and directly inheriting from AbstractCanvas class allowed for easy handling of the size (probably can cause some conflict later with matplotlib context being invoked as well).
